version: "3.8"
services:
  db:
    container_name: legosets-db
    image: postgres:14.1-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d
  api:
    container_name: legosets-api-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    volumes:
      - ./src:/app/src
volumes:
  db:
    driver: local
